#!/bin/sh
query=$(printf '%s' "$*" | tr ' ' '-' )
dwnpage=$(curl -s https://www.1377x.to/search/$query/1/ | grep -Po "torrent/[0-9]*/[a-zA-Z0-9.-]*"| head -n 1)
movie=$(curl -s https://www.1377x.to/$dwnpage | grep -Po "magnet:\?xt=urn:btih:[a-zA-Z0-9]*" | head -n 1)
webtorrent "$movie" --mpv
