#!/bin/sh

query=$(printf '%s' "$*" | tr ' ' '-' )
sudo protonvpn c -f

movie=$(curl -s https://eztv.re/search/$query | grep -Po "magnet:\?xt=urn:btih:[a-zA-Z0-9]*" | head -n 1)
sudo protonvpn d 
webtorrent "$movie" --mplayer
